// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfdVoE3suo9badvs4UEeJybNrgM1ntsYg',
    appId: '1:452549042160:web:1cbcb8575095b88d250735',
    messagingSenderId: '452549042160',
    projectId: 'fb-project2-c7018',
    authDomain: 'fb-project2-c7018.firebaseapp.com',
    databaseURL: 'https://fb-project2-c7018-default-rtdb.firebaseio.com',
    storageBucket: 'fb-project2-c7018.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACIVcQWVRi0WD6OzEisqmYrJSe5Kefeh0',
    appId: '1:452549042160:android:63659c912c0ffee5250735',
    messagingSenderId: '452549042160',
    projectId: 'fb-project2-c7018',
    databaseURL: 'https://fb-project2-c7018-default-rtdb.firebaseio.com',
    storageBucket: 'fb-project2-c7018.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA06tIUTvJOTe65P4_u5k_QbwYMwYxXt-Y',
    appId: '1:452549042160:ios:00c40a145e8be8f1250735',
    messagingSenderId: '452549042160',
    projectId: 'fb-project2-c7018',
    databaseURL: 'https://fb-project2-c7018-default-rtdb.firebaseio.com',
    storageBucket: 'fb-project2-c7018.appspot.com',
    iosBundleId: 'com.example.fbProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA06tIUTvJOTe65P4_u5k_QbwYMwYxXt-Y',
    appId: '1:452549042160:ios:d9a68a5e8f3bccbe250735',
    messagingSenderId: '452549042160',
    projectId: 'fb-project2-c7018',
    databaseURL: 'https://fb-project2-c7018-default-rtdb.firebaseio.com',
    storageBucket: 'fb-project2-c7018.appspot.com',
    iosBundleId: 'com.example.fbProject.RunnerTests',
  );
}
